### ISSUE TITLE
Right-clicking a lost miner with golden lasso keeps droping emeralds

### ISSUE THREAD

**Issue by Jwigou** [Daveyx0/PrimitiveMobs#128]
I don't know if it's primitive mobs fault or extra utilities fault, but when you capture a lost miner with a golden lasso in the surface he drops emeralds, and when you release and recapture him, he still drops emerald, it's a really bad thing and it opens the door for cheating emeralds.
I tried posting the issue to extra utilities author but I can't find a way to contact him.

**Comment by Daveyx0** [comment]
This is likely because there were some saving issues with the Lost Miner. Could you check if its fixed in the 1.2 alpha if you have time? Thanks!

**Comment by Daveyx0** [comment]
And sorry for the late response

**Comment by Jwigou** [comment]
It's still the same in 1.2 alpha, but I doubt it's primitive mobs fault cause when I tried the imprisonment tool from Industrial forgoing, it was working just fine.

**Comment by Jwigou** [comment]
the 1.2 update is awesome though, I love it

**Comment by mser7** [comment]
You can fix this by making the miner to check for the condition and reward you himself, instead of you right-click to receive the emeralds

This one is inside a village, have access to sky, yet is still "lost"
https://imgur.com/syphF9g

**Comment by Daveyx0** [comment]
I can make it so you need empty hands to do it; that should fix it as well.
Actually I just did for the next version.

**Comment by mser7** [comment]
Carry On mod issue incoming

**Comment by Jwigou** [comment]
that should resolve the issue, thanks man :)

**Comment by Daveyx0** [comment]
This has been added in 1.2.1, please also update MultiMob for that version :)
